config/routes.rb
RubyVideo::Application.routes.draw do
  devise_for :users
    root :to => "rooms#index"
  resources :rooms
  match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
match '/rooms/party', :controller => 'rooms', :action => 'destroy', :via => :get

end

app/models/room.rb
class Room < ActiveRecord::Base
has_many :users
validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
belongs_to :room
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!


   protected

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	#Dokumentacja OpenTok https://github.com/opentok/Opentok-Ruby-SDK/blob/master/doc/reference.md
	# Metoda config_opentok - wywoływana jest jako pierwsza
	before_filter :config_opentok,:except => [:index]
  before_filter :authenticate_user!
  before_filter :current_user_loged
  before_filter :current_room, :only => [:destroy,:party]
  before_filter :user_outside_room, :only =>[:index]

  def index
  # Uzytkownicy w pokojach
  @all_users= User.where.not(:room_id => nil).order("room_id DESC")
  # Publiczne pokoje
	@rooms = Room.where(:public => true).order("created_at DESC")
  # Tworzenie pokoju
  @new_room = Room.new
 
  end

    def create
    params.permit! 
    session = @opentok.create_session request.remote_addr
    params[:room][:sessionId] = session.session_id



    @new_room = Room.new(params[:room])

    respond_to do |format|
      if @new_room.save
        format.html { redirect_to("/party/"+@new_room.id.to_s) }
      else
        format.html { render :controller => 'rooms',
          :action => "index" }
      end
    end
  end

def destroy
@room.destroy
respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
    flash[:success] = "Room deleted."


end

  def party
    #Dopisanie uzytkownika do pokoju
   	user_in_room = User.find(@user_id)
    user_in_room.room_id = @room.id
    user_in_room.save


#Inicjacja obiektu OpenTok     
role = OpenTok::RoleConstants::MODERATOR
connection_data = current_user.id
@tok_token = @opentok.generate_token :session_id =>@room.sessionId,:role=>role, :connection_data => connection_data.to_s
   
  end
 
  def config_opentok
  		api_key= '44727722'
  		api_secret = '29e97866780941ea936106816a02ccf53c02a704'
  	if @opentok.nil?
 
     @opentok = OpenTok::OpenTokSDK.new api_key,api_secret
    end
  end

private
  def current_user_loged
    if current_user
     @user_name = current_user.email
     @user_id = current_user.id
   else
     redirect_to new_user_session_path, notice: 'Zostałeś wylogowany.'
   end
  end

  private
      def current_room
        @room = Room.find(params[:id])
        @all_user = @room.users
        @room_name = @room.name
      end

private
      def all_rooms_with_users

      end

private
      def user_outside_room
        user_in_room = User.find(@user_id)
        user_in_room.room_id = nil
        user_in_room.save

      end




end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsVChat</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">


       <div class="row">
            <div class="col-lg-12">
    <nav class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">

        <div class="container">

            <div class="navbar-header">

                <!-- Przycisk, który pojawia sie na urzadzeniach mobilnych lub przy zminimalizowanej przegladarce  -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".MenuCollapse">

                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
      <a class="brand" href="#">
                   <i style="padding-right:40px;" class="glyphicon glyphicon-facetime-video"></i>
                </a>


            </div>
            <div style="font-size:40px;"> <%= link_to "RailsVChat", '#', id: "logo" %></div>
            <div class="collapse navbar-collapse MenuCollapse">
               <!-- <%=link_to "Label", :controller => :rooms, :action => :index %>> -->
                <ul id="menu" class="nav navbar-nav navbar-right">
                <li><%= link_to 'Poczekalnia', root_path%> </li>
        			<li id="logo"><%=@user_name%> </li>
                    <li id="io">
                    		<%if user_signed_in? %>
								<%= link_to "Wyloguj", destroy_user_session_path, :method => :delete %>
							<% else %>
								<%= link_to "Logowanie", new_user_session_path %>
							<% end %>
                    </li>               
                </ul>
            </div>
    
        </div>
      
    </nav>
</div>
</div>

      

<% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value %>
        </div>
  <% end %>

<%= yield %>

</div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyVideo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">


       <div class="row">
            <div class="col-lg-12">
    <nav class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">

        <div class="container">

            <div class="navbar-header">

                <!-- Przycisk, który pojawia sie na urzadzeniach mobilnych lub przy zminimalizowanej przegladarce  -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".MenuCollapse">

                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
      
				<a class="brand" href="index.html">
                   <i style="padding-right:40px;" class="glyphicon glyphicon-facetime-video"></i>
                </a>
            
            </div>
            <div style="font-size:40px;"> <%= link_to "RailsVChat", '#', id: "logo" %></div> 
            <div class="collapse navbar-collapse MenuCollapse">

                <ul id="menu" class="nav navbar-nav navbar-right">
        			<li id="logo"><%=@user_name%> </li>
                    <li id="io">
                    		<%if user_signed_in? %>
								<%= link_to "Wyloguj", destroy_user_session_path, :method => :delete %>
							<% else %>
								<%= link_to "Logowanie", new_user_session_path %>
							<% end %>
                    </li>               
                </ul>
            </div>
    
        </div>
      
    </nav>
</div>
</div>





<%= yield %>


<% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value %>
        </div>
  <% end %>
<!-- <p id="notice"><%= notice %></p> -->
</div>
</body>
</html>

app/views/rooms/config_opentok.html.erb
<h1>Rooms#config_opentok</h1>
<p>Find me in app/views/rooms/config_opentok.html.erb</p>
  <% if current_user.admin?%>
            <td><%= link_to 'Usuń', room, method: :delete, data: { confirm: 'Napewno?' } %></td>
        <% end %>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/index.html.erb
<div class="row">
            <div class="col-lg-4">
<div class="well">
<div id="newRoom">


  <fieldset>
	<legend>Stwórz nowy pokój</legend>


<%= form_for(@new_room) do |f| %>
 <%= f.error_messages %>
	Nazwa pokoju <%= f.text_field :name %><br/><br/>
	Czy ma być publiczny?<%= f.check_box :public %><br/><br/>

	<%= f.submit %>
<% end %>

</fieldset>
</div>
</div>
</div>
 <div class="col-lg-8">
<div class="well">
<fieldset>
  <legend>Istniejące pokoje</legend>
  <table cellpadding="2" cellspacing="5">
    <tr>
      <th>Nazwa</th>
      <th>Liczba użytkowników</th>
      <th>Utworzony</th>

          <th>Usuń</th>

    </tr>

    <% @rooms.each do |room| %>
      <tr>
        <td align="center" width="300px"><a href="/party/<%= room.id %>"><%= room.name %></a></td>
        <td align="center" width="300px">  <%= room.users.count%>  </td>
        <td align="center" width="300px"><%= room.created_at %></td>
   
            <td><%= link_to 'Usuń', room, method: :delete, data: { confirm: 'Napewno?'} %></td>
       


      </tr>
    <% end %>
  </table>
</fieldset>
</div>
</div>
</div>
<div class="well">
<fieldset>
  <legend>Użytkownicy w pokojach</legend>
<table class="table table-bordered table-condensed table-hover">
<thead>
    <tr>
     <th>Nazwa pokoju</th>
      <th>Nazwa uzytkownika</th>
      <th>ID pokoju</th>

    </tr>
 </thead>
 <tbody>
    <% @all_users.each do |users| %>
      <tr>
         <td align="center" width="300px"> <%= Room.find(users.room_id).name%></td>
        <td align="center" width="300px"><%= users.email %></td>
        <td align="center" width="300px"> <%= users.room_id%>  </td>
       
   
            
       


      </tr>
    <% end %>
 </tbody>
</table>
</fieldset>

</div>

app/views/rooms/party (copy).html.erb
<!-- Wyświetlenie wszystkich użytkowników w pokoju -->
<fieldset>
  <legend>Użytkownicy w pokoju</legend>
  <table cellpadding="2" cellspacing="5">
    <tr>
      <th>Email</th>
      <th>Id</th>
       </tr>

    <% @all_user.each do |alluser| %>
      <tr>
        <td align="center" width="300px"><%= alluser.email %></a></td>
        <td> <%= alluser.id%>  </td>
        
      </tr>
    <% end %>
  </table>
</fieldset>

<%= link_to 'Poczekalnia', rooms_path(@rooms) %>

<div id="videobox">

</div>


<!-- <script src="http://static.opentok.com/v0.91/js/TB.min.js" type="text/javascript"></script> -->
<script src="//static.opentok.com/webrtc/v2.2/js/opentok.min.js" ></script>
<script type="text/javascript">
	var apiKey =  44727722;
	var sessionId = "<%= @room.sessionId %>";
	var token = "<%= @tok_token %>";
  var name = "<%= @sheets %>";
	var session;
        

//	TB.addEventListener('exception', exceptionHandler);
	

	//Video chat event listeners
	//session.addEventListener('sessionConnected', sessionConnectedHandler);
	//session.addEventListener('streamCreated', streamCreatedHandler);
    //session.addEventListener('streamDestroyed', streamDestroyedHandler);


TB.setLogLevel(TB.DEBUG);
//session.connect(apiKey, token);
   var session = TB.initSession(sessionId);
    session.addEventListener('sessionConnected', sessionConnectedHandler);
    session.addEventListener('streamCreated', streamCreatedHandler);
    session.connect(apiKey, token);


 var publisher;
    function sessionConnectedHandler(event) {
      publisher = TB.initPublisher(apiKey, 'videobox', {name: "<%=@current_user_chat%>"});
      session.publish(publisher);





      // Subscribe to streams that were in the session when we connected
      subscribeToStreams(event.streams);
    }

    function streamCreatedHandler(event) {
      // Subscribe to any new streams that are created
      subscribeToStreams(event.streams);
    }

    function subscribeToStreams(streams) {
      for (var i = 0; i < streams.length; i++) {
        // Make sure we don't subscribe to ourself
        if (streams[i].connection.connectionId == session.connection.connectionId) {
          return;
        }
alert(streams.length);
        // Create the div to put the subscriber element in to
        var div = document.createElement('div');
        div.setAttribute('id', 'stream' + streams[i].streamId);
        document.body.appendChild(div);

        // Subscribe to the stream
        session.subscribe(streams[i], div.id);
      }
    }

</script>

app/views/rooms/party.html.erb
<!-- <div id="invitation">Witaj w kanale  <%=@room_name%> Zaproś znajomych do konferencji dzięląć się tym liniem http://localhost:3000/party/<%= @room.id %></div> -->
<!-- <p><%=@room_name%></p> -->
 <div id="layoutContainer">
        <div id="publisherContainer"></div>
    </div>


 <script src="https://swww.tokbox.com/webrtc/v2.2/js/TB.min.js" type="text/javascript" charset="utf-8"></script>
   <script src="https://code.jquery.com/jquery-1.6.2.min.js" type="text/javascript" charset="utf-8"></script>
  <script src="http://rubyonrails.bl.ee/opentok-layout.min.js" type="text/javascript" charset="utf-8"></script>
      <style type="text/css" media="screen">
     
         #layoutContainer {
                position: absolute;
                top: 110px;
                left: 0;
                right: 0;
                bottom: 0;
                background-color: #B02B2C;
            }
            
            #layoutContainer > div {
                background-color: #B02B2C;
                display: inline-block;
                border: 1px solid #fff;
            }
    </style>
<script type="text/javascript">

////Jednokrotne przeladowanie strony////////////////
 $(document).ready(function(){

//Check if the current URL contains '#' 
if(document.URL.indexOf("#")==-1)
{
// Set the URL to whatever it was plus "#".
url = document.URL+"#";
location = "#";

//Reload the page
location.reload(true);

}
});
//////////////////////////////////////////////////

	var apiKey =  44727722;
	var sessionId = "<%= @room.sessionId %>";
	var token = "<%= @tok_token %>";
  var name = "<%= @user_name %>";
	var session;
   var layoutContainer = document.getElementById("layoutContainer");

    var layout = TB.initLayoutContainer(layoutContainer).layout;    
 
 var session = TB.initSession(sessionId);
    session.on("streamCreated", function(event){
        session.subscribe(event.stream, "layoutContainer", {
            insertMode: "append"
        });
        layout();
    }).connect(apiKey, token, function (err) {
        if (!err) {
            var publisher = OT.initPublisher("publisherContainer",{name: "<%= @user_name %>" });
            session.publish(publisher);
            layout();
        }
    });
var resizeTimeout;
        window.onresize = function() {
          clearTimeout(resizeTimeout);
          resizeTimeout = setTimeout(function () {
            layout();
          }, 20);
        };
        
        $("#layoutContainer>*").live("dblclick", function () {
            if ($(this).hasClass("OT_big")) {
                $(this).removeClass("OT_big");
            } else {
                $(this).addClass("OT_big");
            }
            layout();
        });





</script>
<!--   <input type="button" value="Connect" id ="connectLink" onClick="javascript:signal()" /> 
 -->